### ISSUE TITLE
Track FX randomize requests

### ISSUE THREAD

**Issue by ThoughtPhotography** [MichaelPilyavskiy/ReaScripts#1]
I've always wanted something like this. :)

I'm wondering if it could be possible to add an option only randomize touched parameters? Maybe click on get parameters, touch the ones you want randomized, then click it again to lock randomization only to those parameters? 

That way we could make slight modifications from a starting point we already like.

Also I'm not sure how feasible this would be, but one one of the worst things about "randomize" functions in most VSTi's is that they randomize things like the pitch and tuning which basically leads unusable out of tune results. 

If parameters containing certain keywords like pitch, tuning, cents, transpose etc. could be ignored for instruments the results are likely to be far better. :)

Melda has an incredible "smart randomize" in all their plugins which is light-years ahead of anything else I've tried and I've always wished there was something similar for third-party VST(i). Much of the "smart" aspect (if I understand correctly) is that it limits the range of randomization based on the values of existing presets. One possibly could be reading a plugin's existing presets (.rpl or .fxb, since they are open standards) and limiting the randomization range to the highest/lowest values of each parameter found in the presets. It would probably be quite a challenge, but thought I'd share the idea anyway...

**Comment by MichaelPilyavskiy** [comment]
Reaper internal values are almost always 0...1 so limits are already exists. Smart randomise also here, see script, you can add "pitch" and "tune" keywords to prevent them from randomize. Touch-to-get-in-random-list I guess will be implemented in the next version. Thanks for reply.

**Comment by ThoughtPhotography** [comment]
Thanks! Would I just add the keywords in the protected table section?

**Comment by MichaelPilyavskiy** [comment]
Yes.

**Comment by MichaelPilyavskiy** [comment]
Partly implemented in 1.1
