### ISSUE TITLE
Problem in opening mpl_RS5k manager(background).lua in REAPER

### ISSUE THREAD

**Issue by mateusnazarioc** [MichaelPilyavskiy/ReaScripts#10]
Hey, how are you? :)
I'm having problem in executing mpl_RS5k manager(background).lua in REAPER. The repository didn't came with this archive, so I copied the code here in github and created an archive with it...but it didn't solve too hahaha
It's appearing this:
![image](https://user-images.githubusercontent.com/44046504/47197860-50650c00-d33f-11e8-9016-85d44af6a1ef.png)

Without the archive, just with the files that downloaded with the repository it's appearing this:
![image](https://user-images.githubusercontent.com/44046504/47197884-725e8e80-d33f-11e8-9a19-948c84f286bf.png)

My /Functions doens't exist...I had to create it too!
Any ideas how to solve this problem?

Thanks!

**Comment by mateusnazarioc** [comment]
So, I've read on the forum some guy with the same problem, and he installed it manully along with the VisualMixer...
Now I'm getting this problem:
![image](https://user-images.githubusercontent.com/44046504/47198408-64f6d380-d342-11e8-8182-455cfbbf20b2.png)

Again, thanks for this repository! It's a great work :)

**Comment by MichaelPilyavskiy** [comment]
The error says you didn`t have installed latest SWS Extension build (or just SWS Extension doesn`t installed).
