### ISSUE TITLE
Hi, i get this message when trying to load it.

### ISSUE THREAD

**Issue by cronopioh** [MichaelPilyavskiy/ReaScripts#12]
mpl_RS5k_manager_obj:lua:1637:attempt to call a nil value (global ´BR_GetMediaTrackByGUID´)
I'm using REAPER v5.983/x64
![rs5kmanager](https://user-images.githubusercontent.com/56178332/66245499-d787cd00-e6d3-11e9-98e0-7c7306d38cce.JPG)

**Comment by MichaelPilyavskiy** [comment]
Hello, install SWS Extension: http://www.sws-extension.org
