### ISSUE TITLE
LearnManager CC value issue with non relative mode

### ISSUE THREAD

**Issue by X-Raym** [MichaelPilyavskiy/ReaScripts#15]
Hi !

The MIDI CC learn manager displays wrong values if non absolute mode is set.

For eg, MIDI CC9 become MIDI CC 521 in the display.

It would be nice if the learn manager was able to find in what relative mode the CC learning is made,
it would then also fix the wrong CC value display !

Thx for your support !

EDIT: I also just found that the other option of CC learn (work with selected track, work with active FX window etc) also shift the real CC value. 

Having this mod displayed in the table will also help !

Best,

**Comment by X-Raym** [comment]
Note that ultraschall functions about FX param learn might help there : https://mespotin.uber.space/Ultraschall/US_Api_Functions.html#AddParmLearn_FXStateChunk

**Comment by MichaelPilyavskiy** [comment]
Thanks, it is bad flag handling, It will be soon deprecated, when LearnEditor will be in more usable stage (it is 1.0 at the moment)
