### ISSUE TITLE
nil value error thrown w/ sidechain scripts

### ISSUE THREAD

**Issue by ageis** [MichaelPilyavskiy/ReaScripts#16]
I'm using Reaper v6.08/x64 on Windows 10, and I have the contents of this entire repository copied to `%APPDATA%\Roaming\REAPER\Scripts\MPL Scripts`. (of course, upon fetching the individual scripts via ReaPack, at first it complained about the availablility of `mpl_Various_functions.lua`).

I have a track selected and a different track underneath my mouse cursor and then I call the action via a keyboard shortcut I created. The result: 😢
```
mpl_Create ReaComp sidechain routing.lua:43: attempt to call a nil value (global 'BR_GetMediaTrackByGUID')
```
and likewise:
```
mpl_Create ReaGate sidechain routing.lua:42: attempt to call a nil value (global 'BR_GetMediaTrackByGUID')
```

Surprised since this is relatively new... I subsequently installed _Various_functions_ as well the way you instruct people to and it has made no difference. 

![reascript_error](https://user-images.githubusercontent.com/1161532/79671950-c8093680-8182-11ea-99d9-646aa9dc814b.png)

**Comment by MichaelPilyavskiy** [comment]
Install [SWS Extension](http://www.sws-extension.org/)

**Comment by ageis** [comment]
Correct, issue resolved. Thank you.
