### ISSUE TITLE
Unexpected behaviour in Specral Edits/mpl_Paste and replace spectral edits to selected item.lua

### ISSUE THREAD

**Issue by LukasNowok** [MichaelPilyavskiy/ReaScripts#18]
When copying spectral edits from an item (using "mpl_Copy selected item spectral edits.lua") and pasting it with "mpl_Paste and replace spectral edits to selected item.lua", it seems to only past the first few edits (in my case its always the first seven edits).
Can anyone replicate this?

I'm running Reaper v6.16 on OSX 10.15.7. Scripts run without error messages.

**Comment by MichaelPilyavskiy** [comment]
I can`t reproduce that. Please attach test project.

**Comment by MichaelPilyavskiy** [comment]
That seems like a parsing bug. I rebuilt from scratch item chunk parser and put all stuff related to spectral-edits into mpl_Spectral Editing Tools. From couple of tests all is fine now.
