### ISSUE TITLE
Sidechain script

### ISSUE THREAD

**Issue by veryextravagant** [MichaelPilyavskiy/ReaScripts#2]
Hi. Loving the sidechain script.

I wonder if some mods would be possible.

Source being a track named "SIDECHAINER"
Destination being selected track
ReaComp using a preset named "Sidechain"

So that way it can be triggered from a toolbar button. Not having to go to the source track is a cool feat.

Best

**Comment by MichaelPilyavskiy** [comment]
Try **[this](https://github.com/MichaelPilyavskiy/ReaScript_Test/blob/master/Beta/mpl_Create%20ReaComp%20sidechain%20routing%20-%20MOD.lua)**

**Comment by veryextravagant** [comment]
Thanks Michael

Tried it and it inserted the ReaComp but did not set it correctly the #3 and 4 inputs in the send, as the original script was doing.
Edit: It did it for the first sidechain created but not for the next ones. Next ones are 1 and 2.
Also, it is not working in Pre-Fader (post FX) mode, wich its a must so you can set the fader to zero and not hear the sidechain signal.

**Comment by MichaelPilyavskiy** [comment]
Should works now (same link)

**Comment by veryextravagant** [comment]
Works! Thanks!

**Comment by veryextravagant** [comment]
Michael,

Do you think there is a way to have the inserted ReaComp instance renamed to be: "Sidechain Comp"?

Best

**Comment by MichaelPilyavskiy** [comment]
I updated script, but it willn`t work as expected.
We have no API for renaming FX so if is definetely pain with trackstatechunks (finding name in right place, replace and set changes to whole track). So I did very rough quick replace which rename all "ReaComp" words on giving track to "Sidechain". Not really what you need, but kinda "works" if you send audio to previously empty track

**Comment by veryextravagant** [comment]
Thanks, Michael. Sadly, this defeats the whole purpose of renaming the comp. The idea is to know at first glance what is it doing and to position it at the end of the chain.
