### ISSUE TITLE
Copy and paste midi note velocities doesn't work on chords

### ISSUE THREAD

**Issue by RichardJECooke** [MichaelPilyavskiy/ReaScripts#23]
Installed using Reapack.
See the video below (deleted in 90 days):

[https://streamable.com/ypoion](https://streamable.com/ypoion)

**Comment by MichaelPilyavskiy** [comment]
Imagine you copy 3 notes velocities and paste into chord with 4 notes. Which order should be applied?

**Comment by RichardJECooke** [comment]
I don't know and have no interest in that question. Why do you ask?

**Comment by MichaelPilyavskiy** [comment]
Because it demonstates that in some cases logic is undefined.
