### ISSUE TITLE
Can't open UI for align takes

### ISSUE THREAD

**Issue by BenTKadar** [MichaelPilyavskiy/ReaScripts#24]
Hi!

I've got the following problem. I'd like to use align takes for my vocals but when I want to use it on its own or through a selected action shortcut I run into the following error: mpl_Align takes.lua:2221: attempt to call a nil value (field 'BR_Win32_WritePrivateProfileString')

Can someone help me out please?
Thanks a lot!
Ben

**Comment by MichaelPilyavskiy** [comment]
You need to install SWS extension. I`ll remove that dependency in the future.

**Comment by MichaelPilyavskiy** [comment]
AlignTakes2 doesn't require SWS extension.
