### ISSUE TITLE
Link gain not working on 'build harmonic series bands'

### ISSUE THREAD

**Issue by jmarcham1983** [MichaelPilyavskiy/ReaScripts#25]
selecting Y for yes doesn't seem to work

**Comment by MichaelPilyavskiy** [comment]
Sorry for long time reply.
Just tested and it works fine on my side (double checkecd it is case insensitive)

**Comment by jmarcham1983** [comment]
it works as long as reaeq plug-in isn't in focus and just the tool is applied to reaeq when in default settings, when I add more bands to the plug-in and run to tool the gain doesn't seem to be linked to all the newly added bands, thanks for a fantastic tool though, I am using mx linux btw

**Comment by MichaelPilyavskiy** [comment]
Link only happen once you run the script. Further added bands are NOT linked.
