### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by michaelmon1203** [MichaelPilyavskiy/ReaScripts#27]
Hi, thanks for this amazing reaper plugin, I want to report two bugs:

1. for Macs, the reapack installation won't work, I'm assuming it's the lacks of Raw folder:
https://github.com/MichaelPilyavskiy/ReaScripts/raw/master/index.xml

2. Once I installed on my windows laptop, I found the learnt mapping for master track is not showing up in the learnEditor.

Hope these can be fixed, really appreciate your work!

**Comment by MichaelPilyavskiy** [comment]
1. Please redirect it here https://github.com/cfillion/reapack
2. Yeah it is not catching mastre track. Sorry this script is obsolete, it will be rewritten after 6.99 if Cockos will add support for learn/linking API.
