### ISSUE TITLE
RS5k manager: Database presets don't load properly

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#28]
Loading the first DB preset for a track works perfectly. But if you want to switch to another one it just doesn't seem to do anything.

Workaround: use the function 'Clear current database map' and after that load the new DB preset. Then it works.

**Comment by MichaelPilyavskiy** [comment]
Added a clear database action before loading for 3.0beta53.
Is that fixed?

**Comment by IOphonics** [comment]
Works perfectly now!
