### ISSUE TITLE
Randomize Track FX parameters: versioning issue

### ISSUE THREAD

**Issue by cfillion** [MichaelPilyavskiy/ReaScripts#3]
Hi,

While tracking down a memory leak bug in ReaPack, I found that your script `Randomize Track FX parameters` has has two equivalent versions `1.01` and `1.1`. As I explained in [this post](http://forum.cockos.com/showpost.php?p=1707548&postcount=484), these are both computed as the same in ReaPack.

1.1beta2 and onward will error out when it finds duplicate (or equivalent) versions to fix the memory leak. I'll also make changes in the indexer to prevent this from happening in the future.

Many solutions are possible depending on how you want to name your versions, but you'll need to manually edit index.xml and remove one of the equivalent versions.

v1.01 and v1.1 cannot co-exist within the same package.

Sorry for the trouble. 😉

**Comment by MichaelPilyavskiy** [comment]
I deleted 1.01, hope I didn`t broke something. Understood about versioning, thanks for note.

**Comment by cfillion** [comment]
It's perfect now, thanks!
