### ISSUE TITLE
RS5k manager: 'New kit' function is not undoable

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#30]
It's probably related to the 'pad replace' issue, because it shows the same symptoms. The names revert when you hit undo, but not the samples.

**Comment by MichaelPilyavskiy** [comment]
Is that fixed for 3.0beta53?

**Comment by IOphonics** [comment]
Problem unfortunately remains.

**Comment by MichaelPilyavskiy** [comment]
It seems I cant fix that.
The code performs is just

>reaper.Undo_BeginBlock2( 0)
>DATA2:Actions_DB_InitRandSamples() 
>reaper.Undo_EndBlock2( 0, 'RS5k manager / Database / New kit', 0xFFFFFFFF )

and i don`t know internal mechanism of REAPER undo when we at complex scripts area. It suppose to [print stuff - do something - print stuff] but unfortunately it does not doing this.

**Comment by MichaelPilyavskiy** [comment]
Ah I see undo history is written but when I open actually Undo history it doesn`t show, it seems a REAPER issue
https://forum.cockos.com/showthread.php?p=2612868#post2612868

**Comment by IOphonics** [comment]
Very interesting. We should let them know.
