### ISSUE TITLE
RS5k manager: moving samples sometimes results in ghost pads

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#31]
Sometimes when you're moving samples it only moves its name, but the sound remains on the previous pad. Which then looks like an empty pad but it plays sounds unexpectedly.

Unfortunately I couldn't find a pattern to reproduce it reliably yet, but it happened several times by now. Maybe you have some intuition where to look.

**Comment by MichaelPilyavskiy** [comment]
I can`t reproduce. If you will have this this again, please send me RPP with a result (and short explanation what is expected, which note supposed, which plays).

**Comment by IOphonics** [comment]
Just tested again. Can't reproduce it either right now. But I'll keep an eye open for it. I'll let you know as soon as I have something.
