### ISSUE TITLE
RS5k manager: Random seed for database operations would be useful

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#32]
At the moment, everytime you open Reaper and hit 'New Kit' once or several times, you end up getting the same kits in the same order. Although this is not really super bad, it wouldn't be hard to fix it (I guess).

I don't know which random function you're using, but I guess defining a seed for it is possible. The easiest, quick and dirty solution (that might probably be totally fine here) would be to use the current time of the OS or something similar on startup of the script.

**Comment by MichaelPilyavskiy** [comment]
Is that fixed for 3.0beta53?

**Comment by IOphonics** [comment]
Yes, you've fixed it. Very nice!
