### ISSUE TITLE
RS5k manager: Make 'Pad overview' navigation more fine grained

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#34]
Is it possible to decrease the stepsize for the 'Pad overview' navigation? At the moment you can only move in steps of 8 pads, which is not too bad, but sometimes a bit annoying.  Maybe 4 is better? Or even 2?
Ideally one could click and drag to navigate it, but I can imagine this to be complicated to implement. Anyway, it's rather low priority.

**Comment by IOphonics** [comment]
Sorry, I got the numbers wrong here. 
At the moment the stepsize is 16 pads and  I'm asking to lower it to 8 or maybe even 4.

**Comment by MichaelPilyavskiy** [comment]
Added an options for 3.0beta55
