### ISSUE TITLE
RS5k manager: Make the last played pad a bit more disctinct

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#35]
Could you please make the last played pad stand out a bit more? Sometimes I can't tell which pad was triggered last just by looking at it. Especially when using different track/pad colors, the thin border around the pad gets kind of indistinguishable.

**Comment by MichaelPilyavskiy** [comment]
Increased frame alpha from 0.7 to 1 for 3.0beta55. All I can.
