### ISSUE TITLE
RS5k manager: Parameter fine control bug/nitpick

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#37]
When you start moving a knob to a certain region and then hit "Ctrl" to make fine adjustments while still holding the mouse key pressed, the parameter jumps to the value you started with when clicking the mouse.
I guess it's intended to press "Ctrl" before clicking on the knob, but it would be really nice if it would also work the other way around.

**Comment by MichaelPilyavskiy** [comment]
Yes, it intended. Thats a bit tricky to deal with such modifiers globally. Sorry, I`m not good at this area so I left it as is. Probably in the future I will try to do something with that (or someone help me with the pull request).
