### ISSUE TITLE
RS5k manager: Improve control behaviour of parameters with bigger range

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#38]
Try to manually drag the 'Tune' parameter down one or two octaves and you'll probably notice a problem (assuming you have the script docked to the bottom as I do). As soon as you'll reach the border of the screen the parameter stops moving. Can you change that?
Sure, you can always right click and type if you want a specific big parameter jump, but for rather sensitive parameters like pitch or filter frequencies it's much better to have a continious controller.

**Comment by MichaelPilyavskiy** [comment]
It seems a Reacript limitation, Cockos probably can fix that on their side.
