### ISSUE TITLE
VSTi from send not found if track has a parent

### ISSUE THREAD

**Issue by cfillion** [MichaelPilyavskiy/ReaScripts#4]
(in "Float instrument relevant to MIDI editor" v1.1)

When the track containing the MIDI take has both a send leading to the instrument and a parent track, the script fails to find the instrument from the send.

It's actually looking for sends in parent track instead because `take_track` is overwritten while looking in the parent tracks.

(I've been able to workaround this by moving the send lookup logic above the parent lookup step, but I don't know if looking in the sends first is the desired behavior)

![Screenshot](https://i.imgur.com/MsckLHW.png)

**Comment by MichaelPilyavskiy** [comment]
hope it fixed now ;)

**Comment by cfillion** [comment]
It works perfectly now, thank you! 😺
