### ISSUE TITLE
RS5k manager: Macro | Erased links don't disappear properly

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#40]
When I erase a link it doesn't disappear until I move the mouse outside the link list section.

**Comment by MichaelPilyavskiy** [comment]
Can`t reproduce this

**Comment by IOphonics** [comment]
I'll show you a recording tomorrow

**Comment by IOphonics** [comment]
The problem is gone. 
Since I changed two things. I noticed that I accidentally installed a 32bit version of the 1103 pre release, so I switched to a 64bit install. And I also got the newest pre release from 1111. Now it works as expected. Sorry for the noise.
