### ISSUE TITLE
Align Takes 2.23 giving script error

### ISSUE THREAD

**Issue by amimakingsense143** [MichaelPilyavskiy/ReaScripts#46]
When using align takes (installed with all the latest SWS actions) I get a script error.
aligntake version 2.23
VariousFunctions 3.55

Reaper version 6.75
64bit

I've tried re-installing aligntake and variousfunctions but same error.  The initial error I recieve tells me to "Switch to Full Mode"

![image](https://user-images.githubusercontent.com/125701844/219795912-a65f8e1e-c34d-49c6-bad7-ceb178c43a22.png)

Followed by this script error.

![image](https://user-images.githubusercontent.com/125701844/219795432-c3d550f4-f123-438c-a2bb-88caa6deea8f.png)

**Comment by MichaelPilyavskiy** [comment]
This should be fixed for 2.24
