### ISSUE TITLE
getting error during ReaScript Update with Reaper

### ISSUE THREAD

**Issue by tormyvancool** [MichaelPilyavskiy/ReaScripts#48]
By updating ReaScript with Reaper, I get this error on your script:
![image](https://github.com/MichaelPilyavskiy/ReaScripts/assets/32305535/a5565381-7be4-4427-8beb-b2363b62c105)

**Comment by MichaelPilyavskiy** [comment]
This is some internal reapack issues, sorry, it is probably better to ask in reapack github page.

**Comment by tormyvancool** [comment]
> This is some internal reapack issues, sorry, it is probably better to ask in reapack github page.

Are you aware I wrote this in the beginning of September 2023 and you replied and considered it in september 2024 ?
