### ISSUE TITLE
Bug in all "FX specific/mpl_Export selected item to RS5k instance*" scripts

### ISSUE THREAD

**Issue by fladd** [MichaelPilyavskiy/ReaScripts#5]
I chop a sample, select all choped items, and call one of the scripts and I get this error:
```
...tems to RS5k instances on selected track (drum mode).lua:60: attempt to call a nil value (field 'BR_GetMediaItemGUID')
```

**Comment by MichaelPilyavskiy** [comment]
Install last SWS extension release

**Comment by MichaelPilyavskiy** [comment]
Can`t reproduce, everything works ok for me. It is problem with "gluing chopped items independently" internal function. So make sure all of selected items are actually audio items and also make sure you have properly defined (existed and have write access) path for renders. You can also give a simple project where I can reproduce this bug (maybe it is not a bug of this script, ex sample paths or glued sample paths have non-Unicode characters and this can cause different problems for REAPER).

**Comment by fladd** [comment]
Updating to the latest SWS extension resolved it. Thanks!
