### ISSUE TITLE
Interactive Toolbar - Add item playrate widget

### ISSUE THREAD

**Issue by TravestyAudio** [MichaelPilyavskiy/ReaScripts#7]
Please add an optional widget which changes item playrate.

This should have at least 4 decimal points, so fine changes can be accomplished.

I achieved this on my machine by substituting D_PITCH for D_PLAYRATE in the GUI and Widgets Item scripts, but I wasn't able to work out how to create my own widget, or how to add more decimal places.
I am not a very good scripter :)

**Comment by MichaelPilyavskiy** [comment]
Added for 1.57
